version: '3'
services:
  mongodb:
    image: "mongo"
    restart: always
    ports:
     - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qE1J81k0
      MONGO_INITDB_DATABASE: filtering-service
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
