#!/usr/bin/env groovy
import groovy.json.JsonOutput

pipeline {

    agent any

    environment {
        registry = "danieltnaves/filtering-service"
        registryCredential = 'dockerhub'
        dockerImage = ''
    }

    stages {
        stage('Build') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true clean package -f ./filtering-service/pom.xml'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true test -f ./filtering-service/pom.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    docker.build(registry + ":$BUILD_NUMBER", "-f ./filtering-service/Dockerfile .")
                    dockerImage = docker.build(registry + ":$BUILD_NUMBER", "-f ./filtering-service/Dockerfile .")
                }
            }
        }

        stage('Publish Docker Image') {
            steps{
                script {
                    docker.withRegistry('', registryCredential) {
                        dockerImage.push()
                    }
                }
            }
        }

    }
}
